//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginInfo
    {
        public int LoginID { get; set; }

        [DisplayName("User")]
        [Required(ErrorMessage = "This firld is required.")]
        public string LoginName { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This firld is required.")]
        public string LoginPassword { get; set; }


        public int UserID { get; set; }
    
        public virtual User User { get; set; }

        [DisplayName("New Password")]
        [DataType(DataType.Password)]
        public string NewPassword1 { get; set; }

        [DisplayName("Re-Enter Password")]
        [DataType(DataType.Password)]
        public string NewPassword2 { get; set; }

        public bool Remember { get; set; }

        public string LoginErrorMessage { get; set; }

        public string ModifyMessage { get; set; }
    }
}
