//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Role
    {
        public Role()
        {
            this.Users = new HashSet<User>();
            this.Menus = new HashSet<Menu>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }

        
        public Nullable<int> Status { get; set; }

        
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }

        
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }

        public List<Role> ListA { get; set; }
        public List<Role> ListB { get; set; }
    }
}
